version: "3"
services:
  postgresdb:
    image: postgres:11.7
    container_name: postgres
    volumes:
      - ./pg_data:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_USER: haxul
      POSTGRES_PASSWORD: hammerhaxul101010hammer
      POSTGRES_DB: vacancydb
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    restart: always
  webapp:
    build: api/
    container_name: springbootapp
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - postgresdb
    environment:
      CONTAINER_DB: postgresdb
      POSTGRES_USER: haxul
      POSTGRES_PASSWORD: hammerhaxul101010hammer
      POSTGRES_DB: vacancydb
  nginx:
    image: nginx:1.17.2-alpine
    container_name: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - webapp
    depends_on:
      - postgresdb
    ports:
      - 80:8989
