server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://db_service_name_in_docker-compose:5432/db_name_in_docker_compose
    username: username_in_docker_compose
    password: password_in_docker_compose
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

headhunter:
  api:
    url: https://api.hh.ru/

logging:
  file:
    name: /home/haxul/Documents/development/vacancy-statistics/api/application.log


