version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres
    volumes:
      - ./pg_data:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_USER: haxul
      POSTGRES_PASSWORD: haxul
      POSTGRES_DB: headhunter
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
    networks:
      - postgres
    restart: always

networks:
  postgres:
    driver: bridge